let modelList = [
  {
    name: '动画变形球',
    url: './gltf/AnimatedMorphSphere/glTF/AnimatedMorphSphere.gltf',
    visible: false,
    count: 0,
    scale: 10,
    type: 'glTF',
    currentCartoon: '',
    isShare: false,
    animationList: ['自旋转', '自由运动', 'Globe'],
  },
  {
    name: '炸弹',
    url: './gltf/BoomBox/glTF/BoomBox.gltf',
    visible: false,
    count: 0,
    scale: 500,
    type: 'glTF',
    currentCartoon: '',
    isShare: false,
    animationList: ['自旋转', '自由运动'],
  },
  {
    name: '马',
    url: './gltf/Horse.glb',
    visible: false,
    count: 0,
    scale: 0.1,
    type: 'glTF',
    currentCartoon: '',
    isShare: false,
    animationList: ['自由运动', '自旋转', 'horse_A_'],
  },
  {
    name: '人',
    url: './gltf/CesiumMan/glTF/CesiumMan.gltf',
    visible: false,
    count: 0,
    scale: 10,
    type: 'glTF',
    currentCartoon: '',
    isShare: false,
    animationList: [
      '自由运动',
      '自旋转',
      'animation_0',
      'animation_1',
      'animation_2',
      'animation_3',
      'animation_4',
      'animation_5',
      'animation_6',
      'animation_7',
      'animation_8',
      'animation_9',
      'animation_10',
      'animation_11',
      'animation_12',
      'animation_13',
      'animation_14',
      'animation_15',
      'animation_16',
      'animation_17',
      'animation_18',
    ],
  },
  {
    name: '卡车',
    url: './gltf/CesiumMilkTruck/glTF/CesiumMilkTruck.gltf',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 10,
    isShare: false,
    animationList: ['自由运动', '自旋转', 'animation_0', 'animation_1'],
  },
  {
    name: '机器人',
    url: './gltf/BotSkinned/glTF-MaterialsUnlit/Bot_Skinned.gltf',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 10,
    isShare: false,
    animationList: ['自由运动', '自旋转', 'Take 001'],
  },

  {
    name: '损坏头盔',
    url: './gltf/DamagedHelmet/glTF/DamagedHelmet.gltf',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 10,
    isShare: false,
    animationList: ['自由运动', '自旋转'],
  },
  {
    name: '鸭子',
    url: './gltf/Duck/glTF/Duck.gltf',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 10,
    isShare: false,
    animationList: ['自由运动', '自旋转'],
  },
  {
    name: '李佩里史密斯',
    url: './gltf/LeePerrySmith/LeePerrySmith.glb',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 10,
    isShare: false,
    animationList: ['自由运动', '自旋转'],
  },

  {
    name: '金属粗糙球',
    url: './gltf/MetalRoughSpheres/glTF/MetalRoughSpheres.gltf',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 10,
    isShare: false,
    animationList: ['自由运动', '自旋转'],
  },
  {
    name: '怪物',
    url: './gltf/Monster/glTF/Monster.gltf',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 1,
    isShare: false,
    animationList: [
      '自由运动',
      '自旋转',
      'animation_0',
      'animation_1',
      'animation_2',
      'animation_3',
      'animation_4',
      'animation_5',
      'animation_6',
      'animation_7',
      'animation_8',
      'animation_9',
      'animation_10',
      'animation_11',
      'animation_12',
      'animation_13',
      'animation_14',
      'animation_15',
      'animation_16',
      'animation_17',
      'animation_18',
      'animation_19',
      'animation_20',
      'animation_21',
      'animation_22',
      'animation_23',
      'animation_24',
      'animation_25',
      'animation_26',
      'animation_27',
      'animation_28',
      'animation_29',
      'animation_30',
      'animation_31',
    ],
  },
  {
    name: '奈芙蒂蒂',
    url: './gltf/Nefertiti/Nefertiti.glb',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 1,
    isShare: false,
    animationList: ['自由运动', '自旋转'],
  },
  {
    name: '轮廓盒子',
    url: './gltf/OutlinedBox/OutlinedBox.gltf',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 0.1,
    isShare: false,
    animationList: ['自由运动', '自旋转'],
  },
  {
    name: '机器人',
    url: './gltf/RobotExpressive/RobotExpressive.glb',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 10,
    isShare: false,
    animationList: [
      '自由运动',
      '自旋转',
      'Dance',
      'Death',
      'Idle',
      'Jump',
      'No',
      'Punch',
      'Running',
      'Sitting',
      'Standing',
      'ThumbsUp',
      'Walking',
      'WalkJump',
      'Wave',
      'Yes',
    ],
  },
  {
    name: '树',
    url: './gltf/tree/tree.glb',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 10,
    isShare: false,
    animationList: ['自由运动', '自旋转'],
  },

  // {
  //   name: 'ferrari',
  //   url: './gltf/ferrari.glb',
  //   type: 'glTF',
  // currentCartoon:"",
  //   visible: false,
  //   count: 0,
  //   scale: 10,
  // },
  {
    name: '火烈鸟',
    url: './gltf/Flamingo.glb',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 0.1,
    isShare: false,
    animationList: ['自由运动', '自旋转', 'flamingo_flyA_'],
  },

  // {
  //   name: 'LittlestTokyo',
  //   url: './gltf/LittlestTokyo.glb',
  //   type: 'glTF',
  // currentCartoon:"",
  //   visible: false,
  //   count: 0,
  //   scale: 10,
  // },
  {
    name: '鹦鹉',
    url: './gltf/Parrot.glb',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 1,
    isShare: false,
    animationList: ['自由运动', '自旋转', 'parrot_A_'],
  },
  {
    name: '主驱动',
    url: './gltf/PrimaryIonDrive.glb',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 10,
    isShare: false,
    animationList: ['自由运动', '自旋转', 'Main'],
  },
  {
    name: '简单皮肤',
    url: './gltf/SimpleSkinning.gltf',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 10,
    isShare: false,
    animationList: ['自由运动', '自旋转', 'Take 01'],
  },
  {
    name: 'SittingBox',
    url: './gltf/SittingBox.glb',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 10,
    isShare: false,
    animationList: ['自由运动', '自旋转'],
  },
  {
    name: '士兵',
    url: './gltf/Soldier.glb',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 10,
    isShare: false,
    animationList: ['自由运动', '自旋转', 'Idle', 'Run', 'TPose', 'Walk'],
  },
  {
    name: '鹳',
    url: './gltf/Stork.glb',
    type: 'glTF',
    currentCartoon: '',
    visible: false,
    count: 0,
    scale: 0.1,
    isShare: false,
    animationList: ['自由运动', '自旋转', 'storkFly_B_'],
  },
]; // 模型列表

let geometryList = [
  {
    name: '立方缓冲几何体',
    type: 'BoxGeometry',
    visible: false,
    count: 0,
    scale: 1,
  },
  {
    name: '管道缓冲几何体',
    type: 'TubeGeometry',
    visible: false,
    count: 0,
    scale: 1,
  },
  {
    name: '挤压缓冲几何体',
    type: 'ExtrudeGeometry',
    visible: false,
    count: 0,
    scale: 1,
  },
  {
    name: '精灵',
    type: 'Sprite',
    visible: false,
    count: 0,
    scale: 1,
  },
]; // 几何体列表

export { modelList, geometryList };
